### ISSUE TITLE
feat: 考虑新增 daemonjob 资源对象

### ISSUE THREAD

**Issue by googs1025** [Operator-Learning-Playground/job-deploy-operator#5]
加入此 controller 对象

```yaml
apiVersion: api.practice.com/v1alpha1
kind: DaemonJob
metadata:
  name: daemonjob-example
spec:
  # 可配置任务流中的全局参数，当设置后会在每个 job 与 pod 中都生效
  globalParams:
    # 可加入 container 所需的参数
    env:
      - name: "FOO"
        value: "bar"
      - name: "QUE"
        value: "pasa"
    # job pod 的 annotations
    annotations:
      key1: value1
      key2: value2
    # job pod 的 labels
    labels:
      key1: value1
      key2: value2
  # 除这些节点之外，都要创建 job    
  excludeNodeList: node-1, node-2
  # 支持原生 job Template 模版  
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: my-container
          image: my-image:latest
          command: [ "echo", "Hello, Kubernetes!" ]
      imagePullSecrets:
        - name: my-registry-secret
    backoffLimit: 3
```
